<configuration>
    <property>
        <name>dfs.namenode.name.dir</name>
        <value>file://${DATA_PATH}/hdfs/namenode</value>
        <final>true</final>
    </property>

    <property>
        <name>dfs.datanode.data.dir</name>
        <value>file://${DATA_PATH}/hdfs/datadata</value>
        <final>true</final>
    </property>

    <property>
        <name>dfs.replication</name>
        <value>${dfs.replication}</value>
    </property>
    <property>
        <name>dfs.blocksize</name>
        <value>268435456</value>
    </property>
    <property>
        <name>dfs.namenode.checkpoint.dir</name>
        <value>file:///${DATA_PATH}/hdfs/sname</value>
        <final>true</final>
    </property>

    <!--https://log.rowanto.com/why-datanode-is-denied-communication-with-namenode
    <property>
        <name>dfs.namenode.datanode.registration.ip-hostname-check</name>
        <value>false</value>
    </property>
   -->


    <property>
        <name>dfs.permissions.enabled</name>
        <value>true</value>
    </property>

    <property>
        <name>dfs.permissions.superusergroup</name>
        <value>hadoop</value>
    </property>

    <!-- https://www.cloudera.com/documentation/enterprise/5-10-x/topics/cdh_ig_hbase_config.html#topic_20_3_4 -->
    <property>
        <name>dfs.datanode.max.transfer.threads</name>
        <value>4096</value>
    </property>
    <property>
        <name>dfs.web.ugi</name>
        <value>${USER_NAME},webgroup</value>
    </property>

</configuration>
